### ISSUE TITLE
Rewrite the README to make it understandable by people who've never used Python

### ISSUE THREAD

**Issue by DrewNeilson** [AB1908/GOG-Galaxy-Export-Script#43] opened 2021-03-12 03:29 UTC
I wanted to use the GOG Galaxy Export Script. I downloaded it, and also downloaded and installed Python 3.9.2, and I have no idea how to use the script, because the README, in its current form, assumes that the reader knows how to use Python.

**Comment by AB1908** [comment] 2021-03-12 03:32
You can actually just double click on the script after installing the necessary dependencies. It should extract all data from the database by default. If you want to control the data being exported, you would need to learn how to use command-line arguments. By "using Python", I assume you imply being able to read and write code in Python and I can confirm that that is not necessary at all. You do have a point about rewriting the readme to make it simpler but I assume that people looking to export to a CSV have the minimal technical expertise required to do so.

**Comment by Abalone75** [comment] 2021-04-02 18:22
Hi AB1908,

I'm such a noob, I just don't know how to use your script :-/ I installed Python, extracted  your files, ran the script in my Downloads-folder - nothing. Put your files into the GOG Galaxy-folder - nothing. Switched to the Wiki-tab and read "GOG Galaxy 2.0 uses an SQLite DB to store game information. This is located at: C:\ProgramData\GOG.com\Galaxy\storage\galaxy-2.0.db" - went to this folder, put your files in it, ran your script - nothing.
I'm out of ideas - could you please help me? :-)

**Comment by PrutskihKA** [comment] 2021-04-04 05:59
> I'm such a noob, I just don't know how to use your script :-/ I installed Python, extracted your files, ran the script in my Downloads-folder - nothing. Put your files into the GOG Galaxy-folder - nothing. Switched to the Wiki-tab and read "GOG Galaxy 2.0 uses an SQLite DB to store game information. This is located at: C:\ProgramData\GOG.com\Galaxy\storage\galaxy-2.0.db" - went to this folder, put your files in it, ran your script - nothing.
> I'm out of ideas - could you please help me? :-)

Hi Abalone75!

You need to run the command line and write "py -V".  Enter. The screen will display "Python 3....".  
If the text does not appear, then the variable path are not configured for Python.

**Comment by AB1908** [comment] 2021-04-05 07:28
@Abalone75, you probably didn't install dependencies. You can go ahead and google how to do that but it's usually a form of installing the packages listed in the Dependencies section using `pip`. I wonder if there's a way to automate this.

**Comment by Abalone75** [comment] 2021-04-07 16:59
@PrutskihKA @AB1908 Thank you both for your help! Your answers didn't connect directly to my problem, but brought me finally on the right track and helped me to learn more about python & co. :-D
My issue was that my vector-graphic-program Inkscape came with its own python-installation - thus every time I installed a package it was installed to Inkscape (Python 3.8) and not to my Python 3.9-folder. After kicking Inkscape from my harddrive everything works like a charm now :-D

**Comment by AB1908** [comment] 2021-07-28 12:49
Since there's been no progress on this, especially from my end, and there have been no other comments, I'm closing this for now. We can always reopen this in the future if it's too difficult to get the script going.

**Closed as completed by AB1908** 2021-07-28 12:49 UTC
